server:
  port: 8083
spring:
  application:
    name: risk-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: risk-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.bank.common.event
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
logging:
  pattern:
    level: "%5p [corr:%X{correlationId:-na}]"
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
---
spring:
  config:
    activate:
      on-profile: k8s
  kafka:
    bootstrap-servers: kafka:9092
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
