version: "3.9"
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_HEAP_OPTS: -Xms128m -Xmx256m
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xms256m -Xmx512m

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile
    depends_on:
      - kafka
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  loan-service:
    build:
      context: .
      dockerfile: loan-service/Dockerfile
    depends_on:
      - kafka
      - customer-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  risk-service:
    build:
      context: .
      dockerfile: risk-service/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    depends_on:
      - customer-service
      - loan-service
      - payment-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  payment-ui:
    build:
      context: .
      dockerfile: payment-ui/Dockerfile
    depends_on:
      - api-gateway
    ports:
      - "4200:80"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./docs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4318:4318"
