server:
  port: 8081
spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/banking
    username: bank
    password: bank
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    level: "%5p [corr:%X{correlationId:-na}]"
---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/banking
  sql:
    init:
      mode: always
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
---
spring:
  config:
    activate:
      on-profile: k8s
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/banking
  sql:
    init:
      mode: always
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
