server:
  port: 8082
spring:
  application:
    name: loan-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
clients:
  customer:
    base-url: http://localhost:8081
resilience4j:
  circuitbreaker:
    instances:
      customerService:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
  bulkhead:
    instances:
      customerService:
        maxConcurrentCalls: 20
        maxWaitDuration: 100ms
  ratelimiter:
    instances:
      customerService:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    level: "%5p [corr:%X{correlationId:-na}]"
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
clients:
  customer:
    base-url: http://customer-service:8081
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
---
spring:
  config:
    activate:
      on-profile: k8s
  kafka:
    bootstrap-servers: kafka:9092
clients:
  customer:
    base-url: http://customer-service:8081
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
