server:
  port: 8082
spring:
  application:
    name: loan-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
clients:
  customer:
    base-url: http://localhost:8081
resilience4j:
  circuitbreaker:
    instances:
      customerService:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
clients:
  customer:
    base-url: http://customer-service:8081
